[build]
  functions = "netlify/functions"

# Functions are automatically detected from netlify/functions directory
# No need to explicitly map them in netlify.toml

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"